// This file is auto-generated by Convex. Do not modify.
import type { DataModel, Id } from "./dataModel";

// Function names
export type FunctionReference =
  | "functions:listMessages"
  | "functions:getMessage"
  | "functions:createMessage"
  | "functions:updateMessage"
  | "functions:deleteMessage";

// API object for useQuery and useMutation calls
export const api = {
  functions: {
    listMessages: {
      name: "functions:listMessages" as const,
      isQuery: true,
      args: {},
    } as const,
    getMessage: {
      name: "functions:getMessage" as const,
      isQuery: true,
      args: { id: "" as Id<"messages"> },
    } as const,
    createMessage: {
      name: "functions:createMessage" as const,
      isQuery: false,
      args: { author: "", body: "" },
    } as const,
    updateMessage: {
      name: "functions:updateMessage" as const,
      isQuery: false,
      args: { id: "" as Id<"messages">, author: "" as string | undefined, body: "" as string | undefined },
    } as const,
    deleteMessage: {
      name: "functions:deleteMessage" as const,
      isQuery: false,
      args: { id: "" as Id<"messages"> },
    } as const,
  },
} as const;

export type Api = typeof api;
