// This file is auto-generated by Convex. Do not modify.
import type { Id } from "./dataModel";

const FUNCTION_NAME = Symbol.for("functionName");

// Create function references with the correct Symbol key
const makeFunctionRef = (name: string) => ({ [FUNCTION_NAME]: name });

// API object for useQuery and useMutation calls
export const api = {
  functions: {
    listMessages: makeFunctionRef("functions:listMessages") as any,
    getMessage: makeFunctionRef("functions:getMessage") as any,
    createMessage: makeFunctionRef("functions:createMessage") as any,
    updateMessage: makeFunctionRef("functions:updateMessage") as any,
    deleteMessage: makeFunctionRef("functions:deleteMessage") as any,
  },
} as any;

export type Api = typeof api;
