/**
 * This file is auto-generated by Convex.
 *
 * DataModel describes the shape of the database tables.
 * It will be updated when you run `npx convex dev`.
 */

export interface DataModel {
  mockData: {
    _id: string;
    _creationTime: number;
    name: string;
    value: string;
    description: string;
  };
}
