// This file is auto-generated by Convex. Do not modify.
import { v } from "convex/values";

export constTableName = "messages" as const;
export type TableNames = typeofTableName;

// System identifier type
export type SystemId = string & { __systemId: never };
export type Id<Table extends TableNames> = `${Table}|${SystemId}`;

export interface DataModel {
  messages: {
    field: {
      author: string;
      body: string;
      createdAt: number;
    };
    // Indexes
    by_creation_time: {
      field: "createdAt";
    };
  };
}

// Document type for messages table
export interface MessageDocument {
  _id: Id<"messages">;
  _creationTime: number;
  author: string;
  body: string;
  createdAt: number;
}
