// This file is auto-generated by Convex. Do not modify.

export type SystemId = string & { __systemId: never };
export type Id<Table extends string> = `${Table}|${SystemId}`;

export interface DataModel {
  messages: {
    field: {
      author: string;
      body: string;
      createdAt: number;
    };
  };
}

export const TableName = "messages" as const;
export type TableNames = typeof TableName;
