// This file is auto-generated by Convex. Do not modify.
import type { DataModel, TableName } from "./dataModel";
import type {
  DocumentNames,
  Document,
  GenericDocument,
} from "convex/server";
import type {
  PropertyValidator,
  DefaultFunction,
  OptionalPropertyValidator,
} from "convex/values";

import {
  query as genericQuery,
  mutation as genericMutation,
  internalQuery as genericInternalQuery,
  internalMutation as genericInternalMutation,
  action as genericAction,
  internalAction as genericInternalAction,
} from "convex/server";

// Function builders
export const query = genericQuery<DataModel>;
export const mutation = genericMutation<DataModel>;
export const internalQuery = genericInternalQuery<DataModel>;
export const internalMutation = genericInternalMutation<DataModel>;
export const action = genericAction<DataModel>;
export const internalAction = genericInternalAction<DataModel>;

// Re-export types
export type { DataModel, TableName };
export type { DocumentByName } from "convex/server";
