// This file is auto-generated by Convex. Do not modify.
import type { DataModel } from "./dataModel";

// Function builders that accept { args?, handler } objects
export const query: any = (config: any) => ({
  ...config,
  _type: "query" as const,
  isQuery: true,
});

export const mutation: any = (config: any) => ({
  ...config,
  _type: "mutation" as const,
  isQuery: false,
});

export const action: any = (config: any) => ({
  ...config,
  _type: "action" as const,
});

export const internalQuery = query;
export const internalMutation = mutation;
export const internalAction = action;

export type { DataModel };
